# Generated by Django 3.2.6 on 2021-08-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todomanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='private',
            new_name='is_private',
        ),
    ]
