# Generated by Django 3.2.6 on 2021-09-02 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todomanager', '0006_alter_todo_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='urgent',
            new_name='important',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='title',
        ),
    ]
